version: '3.9'

services:
  palworld:
    image: ${REPOSITORY}:${VERSION}
    container_name: server-downloader
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    volumes:
      - type: bind
        source: ${DOWNLOAD_FOLDER}
        target: /downloaded
    restart: no